# Install nodejs 18.12.0
FROM node:18.12.0-buster

# Set the label for the image
LABEL Name=Node-dev-18.12.0 Version=0.0.1
# Set to nointeractive mode
ENV DEBIAN_FRONTEND=noninteractive
ENV NODE_ENV=development


# Ajust timezone
RUN   apt-get update && apt-get install -y --no-install-recommends \
    locales \
    tzdata \
    ca-certificates \
    libpq-dev \
    && echo "America/Caracas" > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && echo 'LANG="en_US.UTF-8"'>/etc/default/locale \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG=en_US.UTF-8 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV TZ=America/Caracas
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Set the working directory
WORKDIR /usr/src/app
ENV PATH=/usr/src/app/node_modules/.bin:$PATH

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies and devDependencies
RUN npm install && npm cache clean --force
RUN mkdir ./node_modules/.cache && chmod -R 777 ./node_modules/.cache

# Copy the rest of the files to the working directory
COPY . .


CMD ["npm", "run", "business-rules:dev"]
